apiVersion: charts.helm.k8s.io/v1alpha1
kind: Unleash
metadata:
  name: example-unleash
spec:
  # Default values copied from <project_dir>/helm-charts/unleash/values.yaml
  
  # Default values for nginx.
  # This is a YAML-formatted file.
  # Declare name/value pairs to be passed into your templates.
  
  replicaCount: 1
  restartPolicy: Never
  
  image:
    repository: unleashorg/unleash-server
    tag: 3.1
    pullPolicy: IfNotPresent
  
  # values for postgresql chart.
  postgresql:
    postgresqlUsername: postgres
    postgresqlPassword: 1234
    postgresqlDatabase: unleash
    service:
      clusterIP: 10.96.0.2
