apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: unleashes.charts.helm.k8s.io
spec:
  group: charts.helm.k8s.io
  names:
    kind: Unleash
    listKind: UnleashList
    plural: unleashes
    singular: unleash
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
